version: '3.9'

services:
    postgresql:
        image: postgres:latest
        container_name: db_go
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: 1234
            POSTGRES_USER: admin
            POSTGRES_DB: db_orders
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - 5050:80
        depends_on:
            - postgresql
        volumes:
            - pgadmin_data:/var/lib/pgadmin

volumes:
    postgres_data:
        driver: local
    pgadmin_data:
        driver: local
